---
- name: Installing MSI
  hosts: all
  gather_facts: false

  tasks:
    - name: Download the installer
      win_get_url:
        url: https://onboardcloud.dl.sourceforge.net/project/sevenzip/7-Zip/23.01/7z2301-x64.msi
        dest: D:\Downloads\7z2301-x64.msi

##- name: Ensure 7-Zip is installed through win_package
 ## win_package:
  ##  path: D:\Downloads\7z2301-x64.msi
 ##   state: present


- name: win_command
  win_command: C:\Windows\System32\msiexec.exe /i D:\Downloads\7z2301-x64.msi /qn /norestart
  when: 7zip_installed.exists == false
